name: test workflow
on:
  - push
jobs:
  myFirstJob:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@V2
      name: show files
      run: ls -la
    - name: Execute the tests
      run: python test.py
